export const browserCoreExamples = [
  "foxclaw browser status",
  "foxclaw browser start",
  "foxclaw browser stop",
  "foxclaw browser tabs",
  "foxclaw browser open https://example.com",
  "foxclaw browser focus abcd1234",
  "foxclaw browser close abcd1234",
  "foxclaw browser screenshot",
  "foxclaw browser screenshot --full-page",
  "foxclaw browser screenshot --ref 12",
  "foxclaw browser snapshot",
  "foxclaw browser snapshot --format aria --limit 200",
  "foxclaw browser snapshot --efficient",
  "foxclaw browser snapshot --labels",
];

export const browserActionExamples = [
  "foxclaw browser navigate https://example.com",
  "foxclaw browser resize 1280 720",
  "foxclaw browser click 12 --double",
  'foxclaw browser type 23 "hello" --submit',
  "foxclaw browser press Enter",
  "foxclaw browser hover 44",
  "foxclaw browser drag 10 11",
  "foxclaw browser select 9 OptionA OptionB",
  "foxclaw browser upload /tmp/foxclaw/uploads/file.pdf",
  'foxclaw browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "foxclaw browser dialog --accept",
  'foxclaw browser wait --text "Done"',
  "foxclaw browser evaluate --fn '(el) => el.textContent' --ref 7",
  "foxclaw browser console --level error",
  "foxclaw browser pdf",
];
